//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.1433
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

namespace MSOpenKMCore.ws
{

    // 
    // Este código fuente fue generado automáticamente por wsdl, Versión=2.0.50727.1432.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "OKMAuthBinding", Namespace = "http://endpoint.ws.openkm.git.es/")]
    public partial class OKMAuthService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback getGrantedRolesOperationCompleted;

        private System.Threading.SendOrPostCallback getGrantedUsersOperationCompleted;

        private System.Threading.SendOrPostCallback getRolesOperationCompleted;

        private System.Threading.SendOrPostCallback getUsersOperationCompleted;

        private System.Threading.SendOrPostCallback grantRoleOperationCompleted;

        private System.Threading.SendOrPostCallback grantUserOperationCompleted;

        private System.Threading.SendOrPostCallback loginOperationCompleted;

        private System.Threading.SendOrPostCallback logoutOperationCompleted;

        private System.Threading.SendOrPostCallback revokeRoleOperationCompleted;

        private System.Threading.SendOrPostCallback revokeUserOperationCompleted;

        /// <remarks/>
        public OKMAuthService(String host)
        {
            if (host.EndsWith("/"))
            {
                this.Url = host + "OKMAuth";
            }
            else
            {
                this.Url = host + "/OKMAuth";
            }
        }

        /// <remarks/>
        public event getGrantedRolesCompletedEventHandler getGrantedRolesCompleted;

        /// <remarks/>
        public event getGrantedUsersCompletedEventHandler getGrantedUsersCompleted;

        /// <remarks/>
        public event getRolesCompletedEventHandler getRolesCompleted;

        /// <remarks/>
        public event getUsersCompletedEventHandler getUsersCompleted;

        /// <remarks/>
        public event grantRoleCompletedEventHandler grantRoleCompleted;

        /// <remarks/>
        public event grantUserCompletedEventHandler grantUserCompleted;

        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;

        /// <remarks/>
        public event logoutCompletedEventHandler logoutCompleted;

        /// <remarks/>
        public event revokeRoleCompletedEventHandler revokeRoleCompleted;

        /// <remarks/>
        public event revokeUserCompletedEventHandler revokeUserCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "http://endpoint.ws.openkm.git.es/", ResponseNamespace = "http://endpoint.ws.openkm.git.es/", Use = System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("value", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bytePair[] getGrantedRoles(string arg0, string arg1)
        {
            object[] results = this.Invoke("getGrantedRoles", new object[] {
                    arg0,
                    arg1});
            return ((bytePair[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetGrantedRoles(string arg0, string arg1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getGrantedRoles", new object[] {
                    arg0,
                    arg1}, callback, asyncState);
        }

        /// <remarks/>
        public bytePair[] EndgetGrantedRoles(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bytePair[])(results[0]));
        }

        /// <remarks/>
        public void getGrantedRolesAsync(string arg0, string arg1)
        {
            this.getGrantedRolesAsync(arg0, arg1, null);
        }

        /// <remarks/>
        public void getGrantedRolesAsync(string arg0, string arg1, object userState)
        {
            if ((this.getGrantedRolesOperationCompleted == null))
            {
                this.getGrantedRolesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetGrantedRolesOperationCompleted);
            }
            this.InvokeAsync("getGrantedRoles", new object[] {
                    arg0,
                    arg1}, this.getGrantedRolesOperationCompleted, userState);
        }

        private void OngetGrantedRolesOperationCompleted(object arg)
        {
            if ((this.getGrantedRolesCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getGrantedRolesCompleted(this, new getGrantedRolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "http://endpoint.ws.openkm.git.es/", ResponseNamespace = "http://endpoint.ws.openkm.git.es/", Use = System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("value", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bytePair[] getGrantedUsers(string arg0, string arg1)
        {
            object[] results = this.Invoke("getGrantedUsers", new object[] {
                    arg0,
                    arg1});
            return ((bytePair[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetGrantedUsers(string arg0, string arg1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getGrantedUsers", new object[] {
                    arg0,
                    arg1}, callback, asyncState);
        }

        /// <remarks/>
        public bytePair[] EndgetGrantedUsers(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bytePair[])(results[0]));
        }

        /// <remarks/>
        public void getGrantedUsersAsync(string arg0, string arg1)
        {
            this.getGrantedUsersAsync(arg0, arg1, null);
        }

        /// <remarks/>
        public void getGrantedUsersAsync(string arg0, string arg1, object userState)
        {
            if ((this.getGrantedUsersOperationCompleted == null))
            {
                this.getGrantedUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetGrantedUsersOperationCompleted);
            }
            this.InvokeAsync("getGrantedUsers", new object[] {
                    arg0,
                    arg1}, this.getGrantedUsersOperationCompleted, userState);
        }

        private void OngetGrantedUsersOperationCompleted(object arg)
        {
            if ((this.getGrantedUsersCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getGrantedUsersCompleted(this, new getGrantedUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "http://endpoint.ws.openkm.git.es/", ResponseNamespace = "http://endpoint.ws.openkm.git.es/", Use = System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("value", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] getRoles(string arg0)
        {
            object[] results = this.Invoke("getRoles", new object[] {
                    arg0});
            return ((string[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetRoles(string arg0, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getRoles", new object[] {
                    arg0}, callback, asyncState);
        }

        /// <remarks/>
        public string[] EndgetRoles(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }

        /// <remarks/>
        public void getRolesAsync(string arg0)
        {
            this.getRolesAsync(arg0, null);
        }

        /// <remarks/>
        public void getRolesAsync(string arg0, object userState)
        {
            if ((this.getRolesOperationCompleted == null))
            {
                this.getRolesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRolesOperationCompleted);
            }
            this.InvokeAsync("getRoles", new object[] {
                    arg0}, this.getRolesOperationCompleted, userState);
        }

        private void OngetRolesOperationCompleted(object arg)
        {
            if ((this.getRolesCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRolesCompleted(this, new getRolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "http://endpoint.ws.openkm.git.es/", ResponseNamespace = "http://endpoint.ws.openkm.git.es/", Use = System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("value", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] getUsers(string arg0)
        {
            object[] results = this.Invoke("getUsers", new object[] {
                    arg0});
            return ((string[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetUsers(string arg0, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getUsers", new object[] {
                    arg0}, callback, asyncState);
        }

        /// <remarks/>
        public string[] EndgetUsers(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }

        /// <remarks/>
        public void getUsersAsync(string arg0)
        {
            this.getUsersAsync(arg0, null);
        }

        /// <remarks/>
        public void getUsersAsync(string arg0, object userState)
        {
            if ((this.getUsersOperationCompleted == null))
            {
                this.getUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUsersOperationCompleted);
            }
            this.InvokeAsync("getUsers", new object[] {
                    arg0}, this.getUsersOperationCompleted, userState);
        }

        private void OngetUsersOperationCompleted(object arg)
        {
            if ((this.getUsersCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUsersCompleted(this, new getUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "http://endpoint.ws.openkm.git.es/", ResponseNamespace = "http://endpoint.ws.openkm.git.es/", Use = System.Web.Services.Description.SoapBindingUse.Literal)]
        public void grantRole(string arg0, string arg1, string arg2, int arg3, bool arg4)
        {
            this.Invoke("grantRole", new object[] {
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    arg4});
        }

        /// <remarks/>
        public System.IAsyncResult BegingrantRole(string arg0, string arg1, string arg2, int arg3, bool arg4, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("grantRole", new object[] {
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    arg4}, callback, asyncState);
        }

        /// <remarks/>
        public void EndgrantRole(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void grantRoleAsync(string arg0, string arg1, string arg2, int arg3, bool arg4)
        {
            this.grantRoleAsync(arg0, arg1, arg2, arg3, arg4, null);
        }

        /// <remarks/>
        public void grantRoleAsync(string arg0, string arg1, string arg2, int arg3, bool arg4, object userState)
        {
            if ((this.grantRoleOperationCompleted == null))
            {
                this.grantRoleOperationCompleted = new System.Threading.SendOrPostCallback(this.OngrantRoleOperationCompleted);
            }
            this.InvokeAsync("grantRole", new object[] {
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    arg4}, this.grantRoleOperationCompleted, userState);
        }

        private void OngrantRoleOperationCompleted(object arg)
        {
            if ((this.grantRoleCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.grantRoleCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "http://endpoint.ws.openkm.git.es/", ResponseNamespace = "http://endpoint.ws.openkm.git.es/", Use = System.Web.Services.Description.SoapBindingUse.Literal)]
        public void grantUser(string arg0, string arg1, string arg2, int arg3, bool arg4)
        {
            this.Invoke("grantUser", new object[] {
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    arg4});
        }

        /// <remarks/>
        public System.IAsyncResult BegingrantUser(string arg0, string arg1, string arg2, int arg3, bool arg4, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("grantUser", new object[] {
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    arg4}, callback, asyncState);
        }

        /// <remarks/>
        public void EndgrantUser(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void grantUserAsync(string arg0, string arg1, string arg2, int arg3, bool arg4)
        {
            this.grantUserAsync(arg0, arg1, arg2, arg3, arg4, null);
        }

        /// <remarks/>
        public void grantUserAsync(string arg0, string arg1, string arg2, int arg3, bool arg4, object userState)
        {
            if ((this.grantUserOperationCompleted == null))
            {
                this.grantUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OngrantUserOperationCompleted);
            }
            this.InvokeAsync("grantUser", new object[] {
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    arg4}, this.grantUserOperationCompleted, userState);
        }

        private void OngrantUserOperationCompleted(object arg)
        {
            if ((this.grantUserCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.grantUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "http://endpoint.ws.openkm.git.es/", ResponseNamespace = "http://endpoint.ws.openkm.git.es/", Use = System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string login(string arg0, string arg1)
        {
            object[] results = this.Invoke("login", new object[] {
                    arg0,
                    arg1});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult Beginlogin(string arg0, string arg1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("login", new object[] {
                    arg0,
                    arg1}, callback, asyncState);
        }

        /// <remarks/>
        public string Endlogin(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void loginAsync(string arg0, string arg1)
        {
            this.loginAsync(arg0, arg1, null);
        }

        /// <remarks/>
        public void loginAsync(string arg0, string arg1, object userState)
        {
            if ((this.loginOperationCompleted == null))
            {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                    arg0,
                    arg1}, this.loginOperationCompleted, userState);
        }

        private void OnloginOperationCompleted(object arg)
        {
            if ((this.loginCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "http://endpoint.ws.openkm.git.es/", ResponseNamespace = "http://endpoint.ws.openkm.git.es/", Use = System.Web.Services.Description.SoapBindingUse.Literal)]
        public void logout(string arg0)
        {
            this.Invoke("logout", new object[] {
                    arg0});
        }

        /// <remarks/>
        public System.IAsyncResult Beginlogout(string arg0, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("logout", new object[] {
                    arg0}, callback, asyncState);
        }

        /// <remarks/>
        public void Endlogout(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void logoutAsync(string arg0)
        {
            this.logoutAsync(arg0, null);
        }

        /// <remarks/>
        public void logoutAsync(string arg0, object userState)
        {
            if ((this.logoutOperationCompleted == null))
            {
                this.logoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlogoutOperationCompleted);
            }
            this.InvokeAsync("logout", new object[] {
                    arg0}, this.logoutOperationCompleted, userState);
        }

        private void OnlogoutOperationCompleted(object arg)
        {
            if ((this.logoutCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.logoutCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "http://endpoint.ws.openkm.git.es/", ResponseNamespace = "http://endpoint.ws.openkm.git.es/", Use = System.Web.Services.Description.SoapBindingUse.Literal)]
        public void revokeRole(string arg0, string arg1, string arg2, int arg3, bool arg4)
        {
            this.Invoke("revokeRole", new object[] {
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    arg4});
        }

        /// <remarks/>
        public System.IAsyncResult BeginrevokeRole(string arg0, string arg1, string arg2, int arg3, bool arg4, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("revokeRole", new object[] {
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    arg4}, callback, asyncState);
        }

        /// <remarks/>
        public void EndrevokeRole(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void revokeRoleAsync(string arg0, string arg1, string arg2, int arg3, bool arg4)
        {
            this.revokeRoleAsync(arg0, arg1, arg2, arg3, arg4, null);
        }

        /// <remarks/>
        public void revokeRoleAsync(string arg0, string arg1, string arg2, int arg3, bool arg4, object userState)
        {
            if ((this.revokeRoleOperationCompleted == null))
            {
                this.revokeRoleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrevokeRoleOperationCompleted);
            }
            this.InvokeAsync("revokeRole", new object[] {
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    arg4}, this.revokeRoleOperationCompleted, userState);
        }

        private void OnrevokeRoleOperationCompleted(object arg)
        {
            if ((this.revokeRoleCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.revokeRoleCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace = "http://endpoint.ws.openkm.git.es/", ResponseNamespace = "http://endpoint.ws.openkm.git.es/", Use = System.Web.Services.Description.SoapBindingUse.Literal)]
        public void revokeUser(string arg0, string arg1, string arg2, int arg3, bool arg4)
        {
            this.Invoke("revokeUser", new object[] {
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    arg4});
        }

        /// <remarks/>
        public System.IAsyncResult BeginrevokeUser(string arg0, string arg1, string arg2, int arg3, bool arg4, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("revokeUser", new object[] {
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    arg4}, callback, asyncState);
        }

        /// <remarks/>
        public void EndrevokeUser(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void revokeUserAsync(string arg0, string arg1, string arg2, int arg3, bool arg4)
        {
            this.revokeUserAsync(arg0, arg1, arg2, arg3, arg4, null);
        }

        /// <remarks/>
        public void revokeUserAsync(string arg0, string arg1, string arg2, int arg3, bool arg4, object userState)
        {
            if ((this.revokeUserOperationCompleted == null))
            {
                this.revokeUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrevokeUserOperationCompleted);
            }
            this.InvokeAsync("revokeUser", new object[] {
                    arg0,
                    arg1,
                    arg2,
                    arg3,
                    arg4}, this.revokeUserOperationCompleted, userState);
        }

        private void OnrevokeUserOperationCompleted(object arg)
        {
            if ((this.revokeUserCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.revokeUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://endpoint.ws.openkm.git.es/")]
    public partial class bytePair
    {

        private string keyField;

        private sbyte valueField;

        private bool valueFieldSpecified;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sbyte value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified
        {
            get
            {
                return this.valueFieldSpecified;
            }
            set
            {
                this.valueFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void getGrantedRolesCompletedEventHandler(object sender, getGrantedRolesCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getGrantedRolesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getGrantedRolesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bytePair[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bytePair[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void getGrantedUsersCompletedEventHandler(object sender, getGrantedUsersCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getGrantedUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getGrantedUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bytePair[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bytePair[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void getRolesCompletedEventHandler(object sender, getRolesCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRolesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getRolesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void getUsersCompletedEventHandler(object sender, getUsersCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void grantRoleCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void grantUserCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void logoutCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void revokeRoleCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void revokeUserCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

}