/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConfirmationForm.java
 *
 * Created on 16-sep-2010, 18:50:40
 */

package com.openkm.openoffice.ui;

import com.openkm.openoffice.OpenKMAddOn;

/**
 *
 * @author Administrador
 */
public class ConfirmationForm extends javax.swing.JFrame {

    public static final int OPERATION_NONE           = 0;
    public static final int OPERATION_CHECKIN        = 1;
    public static final int OPERATION_CANCELCHECKIN  = 2;
    public static final int OPERATION_DOCUMENT_ADDED  = 3;
    private int operation = OPERATION_NONE;
    private String documentPath = "";

    /** Creates new form ConfirmationForm */
    public ConfirmationForm(String key, int operation, String documentPath) {
        this.operation = operation;
        this.documentPath = documentPath;
        initComponents();
        setLocationByPlatform(true);
        setLocationRelativeTo(getParent());
        setTitle(OpenKMAddOn.get().getLang().getString("confirmation.title"));
        yesButton.setText(OpenKMAddOn.get().getLang().getString("button.yes"));
        noButton.setText(OpenKMAddOn.get().getLang().getString("button.no"));
        closeButton.setText(OpenKMAddOn.get().getLang().getString("button.close"));
        questionLabel.setText(OpenKMAddOn.get().getLang().getString(key));
        if (operation==OPERATION_DOCUMENT_ADDED) {
            yesButton.setVisible(false);;
            noButton.setVisible(false);
            closeButton.setVisible(true);
        } else  {
            yesButton.setVisible(true);;
            noButton.setVisible(true);
            closeButton.setVisible(false);
        }
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yesButton = new javax.swing.JButton();
        noButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        questionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        yesButton.setText("Yes");
        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButtonActionPerformed(evt);
            }
        });

        noButton.setText("No");
        noButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        questionLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(yesButton)
                        .addGap(18, 18, 18)
                        .addComponent(closeButton)
                        .addGap(18, 18, 18)
                        .addComponent(noButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(questionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(questionLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noButton)
                    .addComponent(closeButton)
                    .addComponent(yesButton))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noButtonActionPerformed
        dispose();
    }//GEN-LAST:event_noButtonActionPerformed

    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButtonActionPerformed
        dispose();
        switch (operation) {
            case OPERATION_CHECKIN :
                OpenKMAddOn.get().executeCheckin(documentPath);
                break;

            case OPERATION_CANCELCHECKIN :
                OpenKMAddOn.get().executeCancelCheckin(documentPath);
                break;
        }
    }//GEN-LAST:event_yesButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton noButton;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables

}
