/**
 *  OpenKM, Open Document Management System (http://www.openkm.com)
 *  Copyright (C) 2006-2010  Paco Avila & Josep Llort
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

package es.git.openkm.frontend.client.panel.center;

import com.google.gwt.user.client.ui.ScrollPanel;
import com.google.gwt.user.client.ui.VerticalPanel;

import es.git.openkm.frontend.client.panel.ExtendedComposite;
import es.git.openkm.frontend.client.widget.resize.HorizontalBar;
import es.git.openkm.frontend.client.widget.searchin.SearchIn;
import es.git.openkm.frontend.client.widget.searchresult.SearchResult;

/**
 * Search panel
 * 
 * @author jllort
 *
 */
public class Search extends ExtendedComposite {
	
	private VerticalPanel panel;
	private VerticalPanel topSearchPanel;
	public VerticalPanel bottomResultPanel;
	private ScrollPanel searchPanel; 
	public SearchIn searchIn;
	public SearchResult searchResult;
	private HorizontalBar horizontalBar;
	
	public int topHeight;
	public int labelHeight= 10;
	public int bottomHeight;
	
	public Search() {
		panel = new VerticalPanel();
		horizontalBar = new HorizontalBar();
		searchIn = new SearchIn();
		searchResult = new SearchResult();
		topSearchPanel = new VerticalPanel();
		bottomResultPanel = new VerticalPanel();
		
		searchPanel = new ScrollPanel(searchIn);
		
		searchPanel.setSize("100%", "100%");
		
		topSearchPanel.setSize("100%", "100%");
		topSearchPanel.add(searchPanel);
		topSearchPanel.setStyleName("okm-Search-Panel");
		
		bottomResultPanel.setSize("100%", "100%");
		bottomResultPanel.add(searchResult);
		
		panel.add(topSearchPanel);
		panel.add(horizontalBar);
		panel.add(bottomResultPanel);
		panel.setVerticalAlignment(VerticalPanel.ALIGN_TOP);
		initWidget(panel);
	}
	
	/**
	 * Refresh language values
	 */
	public void langRefresh() {
		searchIn.langRefresh();	
		searchResult.langRefresh();
	}
	
	/**
	 * Sets the size on initialization
	 * 
	 * @param width The max width of the widget
	 * @param height The max height of the widget
	 */
	public void setSize(int width, int height) {
		//topHeight = (height-labelHeight)/3;
		topHeight = 237;
		bottomHeight = height - (topHeight + labelHeight);
		panel.setSize(""+width, ""+height);
		topSearchPanel.setSize(""+width, ""+topHeight);
		// We substract 2 pixels for width and heigh generated by border line
		searchPanel.setSize(""+(width-2), ""+(topHeight-2));
		horizontalBar.setSize(""+width, ""+labelHeight);
		bottomResultPanel.setPixelSize(width, bottomHeight);
		// Resize the scroll panel on tab properties 
		// We substract 2 pixels for width and heigh generated by border line
		searchResult.setPixelSize(width-2, bottomHeight-2);
		searchResult.fixWidth();
	}
	
	/**
	 * Set the size on resize
	 * 
	 * @param width The max width of the widget
	 * @param topHeight The height of the center top panel
	 * @param height The total heigh of top / bottom panels
	 */
	public void setSize(int width, int topHeight, int height) {
		this.topHeight = topHeight;
		bottomHeight = height - (this.topHeight + labelHeight);
		panel.setSize(""+width, ""+height);
		topSearchPanel.setSize(""+width, ""+topHeight);
		// We substract 2 pixels for width and heigh generated by border line
		searchPanel.setSize(""+(width-2), ""+(topHeight-2));
		horizontalBar.setSize(""+width, ""+labelHeight);
		bottomResultPanel.setPixelSize(width, bottomHeight);
		// Resize the scroll panel on tab properties 
		// We substract 2 pixels for width and heigh generated by border line
		searchResult.setPixelSize(width-2, bottomHeight-2);
		searchResult.fixWidth();
	}
	
	/**
	 * Value of the center top panel
	 *  
	 * @return The value of the center top panel
	 */
	public int getTopHeight() {
		return topHeight;
	}
}